# Generated by Django 2.0.2 on 2020-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200206_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(),
        ),
    ]
