# Generated by Django 2.0.2 on 2020-02-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='color',
        ),
    ]
