# Generated by Django 2.0.2 on 2020-02-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_blog_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('pink', 'pink'), ('blue', 'blue')], default='green', max_length=50),
        ),
    ]
